name:                caffe2-cpp
version:             0.1.0.0

extra-source-files:
  - README.md
  - cpp/*.cpp
  - cpp/*.hpp

dependencies:
  - base
  - caffe2-generator

custom-setup:
  dependencies:
    - base
    - Cabal
    - hoppy-runtime >= 0.5 && < 0.6

library:
  source-dirs:      src
  exposed-modules:
    - Caffe2.Cpp
