name:                caffe2-generator
version:             0.1.0.0

dependencies:
  - base

library:
  source-dirs:      src

executables:
  caffe2-generator:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - hoppy-generator
      - hoppy-std
